# https://taskfile.dev/
version: "3"

vars:
  PYTHON_BIN: python3.7
  VENVS: ./venvs/
  FLIT_ENV:   "{{.VENVS}}flit"
  TEST_ENV: "{{.VENVS}}tests"
  NPROC:
    sh: nproc

env:
  FLIT_ROOT_INSTALL: "1"

tasks:
  venv:create:
    status:
      - "test -f {{.ENV}}/bin/activate"
    cmds:
      - "{{.PYTHON_BIN}} -m venv {{.ENV}}"
      - "{{.ENV}}/bin/python3 -m pip install -U pip setuptools wheel"
  flit:init:
    status:
      - "test -f {{.FLIT_ENV}}/bin/flit"
    deps:
      - task: venv:create
        vars:
          ENV: "{{.FLIT_ENV}}"
    cmds:
      - "{{.FLIT_ENV}}/bin/python3 -m pip install flit"
  flit:install:
    sources:
      - pyproject.toml
      - "{{.ENV}}/bin/activate"
    deps:
      - flit:init
      - task: venv:create
        vars:
          ENV: "{{.ENV}}"
    cmds:
      - >
        {{.FLIT_ENV}}/bin/flit install
        --python={{.ENV}}/bin/python3
        --deps=production
        --extras={{.EXTRA}}

  flake8:install:
    status:
      - "test -f {{.TEST_ENV}}/bin/flake8"
    deps:
      - task: venv:create
        vars:
          ENV: "{{.TEST_ENV}}"
    cmds:
      - "{{.TEST_ENV}}/bin/python3 -m pip install -r requirements-flake.txt"
  flake8:run:
    sources:
      - "**/*.py"
    deps:
      - flake8:install
    cmds:
      - "{{.TEST_ENV}}/bin/flake8 ."

  mypy:run:
    deps:
      - task: flit:install
        vars:
          ENV: "{{.TEST_ENV}}"
          EXTRA: tests
    cmds:
      - "{{.TEST_ENV}}/bin/mypy"

  pytest:run:
    deps:
      - task: flit:install
        vars:
          ENV: "{{.TEST_ENV}}"
          EXTRA: tests
    cmds:
      - "{{.TEST_ENV}}/bin/pytest -n {{.NPROC}} {{.CLI_ARGS}}"

  isort:run:
    sources:
      - "**/*.py"
    deps:
      - task: flit:install
        vars:
          ENV: "{{.TEST_ENV}}"
          EXTRA: tests
    cmds:
      - "{{.TEST_ENV}}/bin/isort ."
