# https://taskfile.dev/
version: "3"

vars:
  PYTHON: python3.7
  VENVS: .venvs
  NPROC:
    sh: nproc

env:
  FLIT_ROOT_INSTALL: "1"

tasks:
  install:base:
    status:
      - test -f .venvs/base/bin/flitenv
    cmds:
      - "{{.PYTHON}} -m venv .venvs/base"
      - .venvs/base/bin/python3 -m pip install -U flitenv pip-tools
  install:test:
    sources:
      - pyproject.toml
      - requirements.txt
    deps:
      - install:base
    cmds:
      - .venvs/base/bin/flitenv test install --venvs={{.VENVS}}
  install:lint:
    sources:
      - pyproject.toml
      - requirements.txt
    deps:
      - install:base
    cmds:
      - .venvs/base/bin/flitenv lint install --venvs={{.VENVS}}

  pytest:run:
    desc: "run Python tests"
    deps:
      - install:test
    cmds:
      - .venvs/base/bin/flitenv test run pytest -n {{.NPROC}} {{.CLI_ARGS}}
  flake8:run:
    desc: "lint Python code"
    deps:
      - install:lint
    cmds:
      - .venvs/base/bin/flitenv lint run flake8 {{.ARGS}} .
  mypy:run:
    desc: "check type annotations"
    deps:
      - install:lint
    cmds:
      - .venvs/base/bin/flitenv lint run mypy {{.ARGS}}
